dist: bionic
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

before_install:
  # Install a later version of sbt-extras to support SBT >=1.0
  - curl -Ls https://git.io/sbt > ~/bin/sbt
  - chmod a+x ~/bin/sbt
  # install jdk is needed for JDK10+
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
    - stage: Node versions
      node_js: 6
      env: JDK=9
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - java -version
        - npm test
        - npm run test-system
    -
      node_js: 8
      env: JDK=10
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - java -version
        - npm test
        - npm run test-system
    -
      node_js: 10
      env: JDK=11
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - npm test
        - npm run test-system
    - stage: Old and newer Java versions
      env: JDK=8
      script:
        - jdk_switcher use openjdk8
        - java -version
        - npm test
        - npm run test-system
    -
      env: JDK=12
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - java -version
        - npm test
        - npm run test-system
    - stage: npm release
      if: branch = master
      node_js: "8" # This *has* to be the "build leader"
      script: skip
      after_success:
        - npx semantic-release
